# Gitpod用 WordPress設定ファイル
tasks:
  - name: Setup WordPress
    init: |
      # 1. WordPress本体をダウンロードして解凍します
      wget https://ja.wordpress.org/latest-ja.tar.gz
      tar -xzf latest-ja.tar.gz
      
      # 2. 私たちのプラグインを正しい場所にコピーします
      cp -r monthly-booking wordpress/wp-content/plugins/
      
      # 3. 設定ファイルのひな形をコピーします
      cd wordpress
      cp wp-config-sample.php wp-config.php
      
      echo "セットアップ準備が完了しました。下のターミナルでサーバーが起動します。"
    command: php -S 0.0.0.0:8000 -t .

ports:
  - port: 8000
    onOpen: open-preview
